### PR TITLE
COBE-1102 bump up Cypress version

### PR DESCRIPTION
**Pull request by ghost**
[workerB](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=K-75Uxs)
[workerB](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=QjUG-Rx)

### CODE REVIEW

**Review by frenchvargulf — APPROVED** [review]
this works right ? xD

**Comment by ghost** [comment]
> this works right ? xD

Does it look like it works?

**Comment by ghost** [comment]
😢

**Comment by frenchvargulf** [comment]
yeah, saw the fails and was like is this right, but also approved in case u needed that

**Comment by mathias-nordicfactory** [comment]
@roberto-albanesi  delete branch? :)

**Comment by ghost** [comment]
It doesn't get deleted automatically? 😱

**Comment by mathias-nordicfactory** [comment]
It wasn't enabled, fixed it for future PRs :)

**Pull request merged**
